name: Deploy Bicep File

on:
  label:
    types:
      - created
  push:
    branches:
      - "main"
  pull_request:
    types: [synchronize, reopened, opened]
    branches:
      - "master"
      - "production"
    paths-ignore:
      - "README.md"
  schedule:
    - cron: '0 0 1 1 *' # once in year at midnight new year eve

env:
  AZURE_RESOURCEGROUP_NAME: demo-apim-graphql
  ENVIRONMENT: nonprod
  LOCATION: "eastus"

jobs:
  Deploy-Bicep-Files:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    outputs:
      RUNNER: ${{ runner.name }}
    steps:

    - name: Get Runner
      run: echo "selected runner = ${{ runner.name }}"

    - name: Checkout code in Runner
      uses: actions/checkout@main

    # Login to Azure
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy APIM service
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./.github//biceps/create_apim_service.bicep
        failOnStdErr: false

    - name: Expose GraphQL API through APIM services
      uses: Azure/cli@v2.0.0
      with:
        inlineScript: |
          az deployment group create \
            --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }} \
            --template-file ./.github/biceps/deploy_graphql_api.bicep

    - name: Configure API Policies
      uses: Azure/cli@v2.0.0
      with:
        inlineScript: |
          echo "Configure API Policies - DONE"

    - name: Configure Product, User, Group and Subscription
      uses: Azure/cli@v2.0.0
      with:
        inlineScript: |
          echo "Configure Product, User, Group and Subscription - DONE"

    - name: Configure Product Policies
      uses: Azure/cli@v2.0.0
      with:
        inlineScript: |
          echo "Configure Product Policies - DONE"

    - name: Configure Developer Portal
      uses: Azure/cli@v2.0.0
      with:
        inlineScript: |
          echo "Configure Developer Portal - DONE"
  
    - name: Clean up resources
      uses: Azure/cli@v2.0.0
      with:
        run: |
          echo "List APIM API(s)"
          az apim api list
          echo "Delete APIM resource by ID"
          run: 'az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RESOURCEGROUP_NAME }}/providers/Microsoft.ApiManagement/service/*'